### PR TITLE
Update readme to contain contribution email and placeholder info

### PR DESCRIPTION
**Pull request by FinlayShepherd**
### Problem
* Readme needs to contain information relevant to readme

### Solution
* Update readme to contain relevant info and placeholder info for later

### CODE REVIEW

**Comment by FinlayShepherd** [comment]
1. Yes although it may be fundamental knowledge about git and therefore not really be appropriate to put in this readme.
2. As far as labels go I think 'enhancement' and 'bug' cover everything we will need (at least for now). I agree there should be some format for defects, I will happily add that to this document.
3. For testing I was planning on using PyTest, I dont know any others at it seems simple, I think we can add more to the testing section once we actually implement any code.

**Comment by FinlayShepherd** [comment]
@NJRBailey ps, I'll add the intention is to use pytest to test section, and will add issue styling to the document

**Comment by FinlayShepherd** [comment]
@NJRBailey I've made changes, what do you think?

**Comment by FinlayShepherd** [comment]
Ok added extra detail, shall i merge?

**Comment by NJRBailey** [comment]
Yep looks good to me

**Pull request merged**
